spring:
  application:
    name: Bot
  datasource:
    url: jdbc:postgresql://localhost:5432/mybotdb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none        # т.к. миграции делает Flyway
      show-sql: true

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
telegram:
  bots:
    bot:
      username: cLLyka_really_bot
      token: 8248269233:AAGoDeG0X0go0VWDevsOPHmIkawzQXlvHDg
